services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: aws-0-us-east-2.pooler.supabase.com
      DB_USERNAME: postgres.slmrcglupqfskshfcsut
      DB_PASSWORD: ZxHI6aX3RmIKo0Sq
      DB_NAME: postgres
      DB_PORT: 5432
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
      JWT_EXPIRES_IN: 1d
      OAUTH2_CLIENT_ID: your_client_id
      OAUTH2_CLIENT_SECRET: your_client_secret
      OAUTH2_CALLBACK_URL: http://localhost:3000/api/auth/callback
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  crm-network:
    driver: bridge
